### ISSUE TITLE
Adding attributes to variant not working

### ISSUE THREAD

**Issue by euperia** [umanit/sylius-product-variant-attribute-plugin#2]
I've started with a clean install of Sylius (1.7.11) with the sample products.

This extension works fine up to the point of adding my new variant attribute to a variant.  I see the 'attributes' tab and it shows the available attributes but does nothing when I select and click the 'Add' button.

![image](https://user-images.githubusercontent.com/2648745/130210709-1fca2c80-ff5d-4f59-8fc9-29b19c82652f.png)

Am I missing something JS related in the install steps? I've rebuilt the assets with `yarn encore dev`.

**Comment by DjLeChuck** [comment]
This plugin does not add any JS, it uses the Sylius one. 

Given that the plugin is only compatible with Sylius `1.8.x` (and soon `1.9.x`), I think there are differences in Sylius `1.7` and `1.8` JS scripts which prevents the operation of the code.

To be sure, I have test the plugin on a fresh Sylius `1.8.12` installation and all is working fine.

**Comment by euperia** [comment]
Revisiting this nearly a year later.  I've updated to Sylius 1.10 and still cannot get this to work.

Can you tell me what supposed to happen when the 'Add attribute' button is clicked?  Does it post/put the entire variant form to `/admin/variant-attribute-forms` and renders the new attributes, or does it do something else?

**Comment by DjLeChuck** [comment]
Hi @euperia ,

Sorry for the delay, I was on vacation. You have delete your message because you've found the problem?

**Comment by euperia** [comment]
@DjLeChuck yes - I had used a fork of this repository (for Sylius 1.7 compatibility) and the forked code had changed the `id` attribute that the Sylius JS uses to add the functionality to the 'add' button.

(The forked repo is https://github.com/urbitech/sylius-product-variant-attribute-plugin)
